### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by endel** [jiborobot/pixi-animate#12]
Hey there,

This project seems interesting, couldn't find usage instructions though. 
I'm currently just trying to figure out how to use it, do you have some caveats? :)

Is there some known issues you're facing right now?

Cheers!

**Comment by bigtimebuddy** [comment]
@endel Currently, we are in a private beta developing an extension for Adobe Animate which publishes animated timeline content for Pixi.js. This repo is the runtime component and probably doesn't make much sense without the extension. Not sure when we're going to release the extension, hopefully soon!

**Comment by herrKlein** [comment]
Hi, 

I am also interested in this project. Is it possible to get involved ? 
Could you share some more information this project and how you think about the native webgl export in animateCC ?

kind regards.

**Comment by perky** [comment]
Any news on that extension? It's exactly the thing I'm looking for :) 👍

**Comment by bigtimebuddy** [comment]
@perky @herrKlein @endel https://github.com/jiborobot/pixi-animate-extension/

**Comment by endel** [comment]
@bigtimebuddy cool. I'll have a look. I actually implemented my own FLA rasterizer script, which works pretty fine. Next year we'll open-source it probably. Cheers!

**Comment by bigtimebuddy** [comment]
The advantage of this extension is that is uses the C++ Adobe Animate SDK to generate the scene graph, so it's pretty fast. It's not a JSFL workflow script but a custom FLA document type. With custom publishing types we can disable certain unsupported features in the interface, like gradients (which are not supported with Pixi Graphics).
