### ISSUE TITLE
Asset Crashing Site on iOS

### ISSUE THREAD

**Issue by GopherwoodTodd** [jiborobot/pixi-animate#34]
We have an animated asset that has a pretty large export from Adobe Animate.

.js file - 700k
shapes file - 3megs

When we use it in our site, it works fine on desktop, but when we load the asset on iOS devices the site crashes shortly after the page loads. 

We're assuming, given that it's only happening on iOS that this is most likely a memory issue. Would that be a fair assessment? Are animations loaded when they are played? Does the memory consumption increase with time? We tried reducing the number of animations it played and that seems to increase the time before the crash.

Do you have any recommendations on the best way to handle this? The asset is composed of vector shapes in Animate as opposed to bitmaps, would converting it to bitmaps help?

Thanks!

**Comment by bigtimebuddy** [comment]
Vectors are generally a terrible idea for lots of complex things. Allocating all that memory with PIXI.Graphics objects is kinda of a mess. My suggestion is that you use this JSFL script (https://github.com/springroll/flashtoolkit#utilitiescopy-layers-to-bitmap) this will convert each frame to a bitmap (non-destructively). It's a little time consuming to convert complex animation, but makes a big difference.

**Comment by GopherwoodTodd** [comment]
Thanks! We'll try this out.

**Comment by bigtimebuddy** [comment]
Any follow-up on this @GopherwoodTodd? Feel free to close if you're satisfied.

**Comment by GopherwoodTodd** [comment]
@bigtimebuddy, yeah that worked. It was a bit of work to get things converted, and the script seemed to fail semi-randomly when trying to convert certain pieces, but we eventually got there. Thank you for the help.
