### ISSUE TITLE
Feature request: property name with instance name as default

### ISSUE THREAD

**Issue by funkypaul** [jiborobot/pixi-animate#40]
Hi!

When putting an instance name for MovieClip in AnimateCC IDE, eg "myButton". would be great to have it available in pixi-animate as name property of that object:

stage.instance.myButton.name = "myButton"

Cheers,
P.

**Comment by bigtimebuddy** [comment]
@funkypaul could you add this to https://github.com/jiborobot/pixi-animate-extension/issues instead?

**Comment by bigtimebuddy** [comment]
Opened a PR for this feature request here: https://github.com/jiborobot/pixi-animate-extension/pull/34
