### ISSUE TITLE
Minify to single file

### ISSUE THREAD

**Issue by nthapaliya** [jiborobot/pixi-animate#44]
What are your thought of minifying the js + txt to a single js file? We plan on creating multiple single-frame graphics as assets and it would be helpful to be able to do so.

Edit: I realize this might be an issue for https://github.com/jiborobot/pixi-animate-extension/ 
Let me know if this is the wrong place.

**Comment by bigtimebuddy** [comment]
This is more of an extension issue. But could you clarify: are you asking to have the graphics draw commands be inline rather than in an external file? 

The reason I set it up this way was because I wanted to make the output more modifiable/readable. Mixing in the graphic draws makes the output much more noisy... this is how the CreateJS output works and I never really liked it. The current setup treats vector graphics very similar to Textures and Spritesheets.

Could you describe your use-case more? What advantage would this have?

**Comment by nthapaliya** [comment]
Thanks, I should have started with my use case. We're learning this tool (pixi-animate) and so I understand we might not be it properly. 

We're porting a flash app to html5 with pixi. We're trying to keep the look and feel of the new app close to the original flash app. We have a few simple static assets such as buttons, icons, etc that we want to use as close to 'vector' like as possible, ie we want to be able to scale and resize them easily without the blurriness that comes from rasterizing. Currently we export them to a png sprite sheet with multiple sizes for various zoom levels, but we're evaluating if we can make them sharper (and reduce download size to the client) by exporting them as pixi graphics objects that it draws on the fly.

**My use case is  this**: The app is written in React, so we want the output to be consumable by webpack. Currently the examples all expect the output js to be imported as `<script>`'s in the html, so I wanted to see if I could remove that restriction. By making it one file I hoped to just modify the output js so it would follow CommonJS module syntax, ie `module.exports = <thing being exported>` and just import it into the other file using `require`. Now I don't see a clear way to do this.

If you have any suggestions I would be glad to hear them.

**Comment by bigtimebuddy** [comment]
In the publish settings in the PixiAnimate formatted FLA, there's an option to make output CommonJS compatible, which adds the `module.exports` business.

**Comment by nthapaliya** [comment]
I'll try this on Monday, thanks you for the suggestion.

**Comment by nthapaliya** [comment]
Stuck with `Uncaught TypeError: Super expression must either be null or a function, not undefined'.`

I was unable to get this to work. `const animate = require('pixi-animate')` fails with the above error. 

We're not using typescript, if that helps. Just regular es6, which is transpiled down to es5.

**Comment by bigtimebuddy** [comment]
I was unable to reproduce this error. Could you please provide more information, or a repo which demonstrates this problem? Also, please provide the version of Node (`node -v`) you're running.

**Comment by nthapaliya** [comment]
My issues turned out to be version issues. I was using the wrong version of pixi for the library. We're stuck at pixi v4.3.0 for the moment, so I downgraded the pixi-animate version so that they were compatible.
