### ISSUE TITLE
SymbolLoader - additional condition

### ISSUE THREAD

**Issue by vlasenkoigor** [jiborobot/pixi-animate#48]
The middleware for parsing flash symbols sometimes fails if resource has not been loaded and iterator function also fails at this point 

`else if (data.nodeName && data.nodeName === 'IMG') {`
 or at this 
`_ShapesCache2.default.add(resource.name, data);`
when we pass empty object as shape data 

In order to have able to continue loading flow even when loading fails (for example we wanna retry loading of this resource) please provide some additional conditions for this function to prevent empty object accces.
My solution is 
if (!data){
            next();
        }else if (url.search(/\.shapes\.(json|txt)$/i) > -1) {
            _ShapesCache2.default.add(resource.name, data);
        } else if (data.nodeName && data.nodeName === 'IMG') {
            // Add individual images to the texture cache by their
            // short symbol name, not the URL
            PIXI.Texture.addTextureToCache(PIXI.Texture.fromFrame(url), resource.name);
        }
        next();

**Comment by bigtimebuddy** [comment]
Sounds good. Would you be interested in putting together a PR for this?

**Comment by helloitsjoe** [comment]
I'm on it! https://github.com/jiborobot/pixi-animate/pull/53
