### ISSUE TITLE
Stopping a MovieClip

### ISSUE THREAD

**Issue by Patrick-Hammond** [jiborobot/pixi-animate#49]
I'd like to play a MovieClip on the timeline once and then stop. Back in the day I would add a frame-script stop() on the last frame of the MovieClip.
When I publish with pixi-animate however, the frame-script doesn't seem to be respected and the MovieClip keeps on playing.
Is there something I'm missing? It's been quite a while since I've done anything in Flash.
I've attached a sample file.
[frameScriptStop.zip](https://github.com/jiborobot/pixi-animate/files/1121490/frameScriptStop.zip)

**Comment by ianmcgregor** [comment]
Hey @Patrick-Hammond, in pixi-animate you need a `this` to scope to the MovieClip you're inside. E.g. `this.stop()`. Have verified using your example file.

**Comment by Patrick-Hammond** [comment]
Aha! Thank you! 👍
