### ISSUE TITLE
Using MovieClips in an existing Pixi application?

### ISSUE THREAD

**Issue by pixelmike** [jiborobot/pixi-animate#50]
Hi, is it possible to add exported MovieClip instances to a pixi stage (PIXI.Container) where we run our own requestAnimationFrame loop? We'd like to be able to add instances, move, scale, rotate, etc. and control playback from JS.

We're evaluating using Adobe Animate to produce animations vs DragonBones or Spine. We're not sure if this export will give us the same flexibility to use animations.

**Comment by bigtimebuddy** [comment]
Yes! you can created a single library clip from the animate output instead of using the entire stage output.
