### ISSUE TITLE
Using gotoAndPlay with lib.stage & nested MovieClips

### ISSUE THREAD

**Issue by kburke3** [jiborobot/pixi-animate#59]
Hello,
I'm trying to use Pixi-Animate and I'm running into issues with gotoAndPlay. When looking at the Javascript file generated by Adobe Animate, I see that the Animate MovieClips inherit the PIXI MovieClip class. It's odd though (and maybe this is simply a misunderstanding of Javascript): I cannot call gotoAndPlay on lib.stage (or any other nested MovieClips). When I look at the Prototype for the object, I see gotoAndPlay (screenshot 1), but not in the instances themselves (screenshot 2). If I call lib.stage.gotoAndPlay("frame_label") it doesn't work. Could you please shed some light on how to work with the main stage timeline and nested timelines with Pixi-Animate? Thank you very much!

Prototype:
![screen shot 2017-11-27 at 4 32 55 pm](https://user-images.githubusercontent.com/33512705/33277547-c85d862e-d390-11e7-8686-954a30be106b.png)

lib.stage:
![screen shot 2017-11-27 at 4 33 04 pm](https://user-images.githubusercontent.com/33512705/33277531-c1b3321a-d390-11e7-8b84-a798fb70a3b5.png)

**Comment by bigtimebuddy** [comment]
The reason is because `lib.stage` is a reference to the stage MovieClip, you actually need to create an instance of it using `new lib.stage()`. However, because all the assets associated with that stage need to be preloaded, the easiest thing to do is to checkout the HTML that's generated when you publish. This creates a PIXI renderer for you.

```js
var scene = new PIXI.animate.Scene(300, 480, {
  view: document.getElementById("stage"),
  backgroundColor: 0xffffff,
  antialias: true
});
scene.load(lib.stage);
```

If you just want to preload and add to an existing PIXI renderer, use the [PIXI.animate.load](http://jiborobot.github.io/pixi-animate/PIXI.animate.html).

```js
const renderer = new PIXI.autoDetectRenderer(1280, 720);
const root = new PIXI.Container();
PIXI.animate.load(lib.stage, root);
function update() {
     renderer.render(root);
     update();
}
update();
```

**Comment by kburke3** [comment]
Thanks for the quick response! Sorry, I'm still a bit confused. In the first PIXI renderer scenario, I do not see gotoAndPlay in the scene instance either. How can I play the scene from frame labels using the generated HTML? Or from nested MovieClip timelines? I see my frame labels ('welcome' and 'loading') being inherited in the .js file, but I'm not sure how to access them.

```javascript
    lib.stage = MovieClip.extend(function () {
		timeline = this;
        MovieClip.call(this, {
            duration: 2,
            framerate: 24,
            labels: {
                loading: 0,
                welcome: 1
            }
        });
```

Thank you!

**Comment by kburke3** [comment]
I think I've figured my problem out (but I'm still glad to know if there's a better way to do this)...

I can reference the MovieClip's labels using:
```javascript
scene.stage.children[0].gotoAndPlay("loading");
```
