### ISSUE TITLE
Creating Dynamic Tweens with Easing

### ISSUE THREAD

**Issue by kburke3** [jiborobot/pixi-animate#61]
Hello,
Sorry for all of the messages and thank you for the help so far (I'm under a deadline). I'm now trying to create Tweens using Pixi Animate.

Currently I'm doing the following:
```javascript
var target = timeline.categories_mc.categories_text_mc;
new PIXI.animate.Tween(target, {y:0}, {y:-200}, 24);
```
Nothing is happening. I also did not see anything in the library or in Pixi specifying eases, your final parameter. What are you looking for with them? Something like this?
```javascript
function (x, t, b, c, d) {
    return c*((t=t/d-1)*t*t + 1) + b;
},
```
Thanks again!

**Comment by bigtimebuddy** [comment]
The Tween class is something used internally by Timeline. You should not instantiate these classes directly. They are there to render animations authored in Animate. If you want to programmatically tween something, use a library like TweenMax or TweenJS.

**Comment by bigtimebuddy** [comment]
And no worries about the questions!
