### ISSUE TITLE
Changing Shapes' Fill colors dynamically

### ISSUE THREAD

**Issue by kburke3** [jiborobot/pixi-animate#64]
Hello!
I'm trying to change the fill color of Shapes dynamically. I've tried a few things with the instances, like changing their fillColor property and drawCommands but is not having an effect. Is this something controlled by the ShapesCache? What is the best practice for updating a Graphic's fill at runtime?

Thank you!

**Comment by bigtimebuddy** [comment]
You cannot change the color of the Graphic after it's been drawn. You'd need to redraw it.

Instead, you could use a ColorMatrixFilter to adjust the color: 
https://jsfiddle.net/bigtimebuddy/Ls1t4yc2/

Documentation for that.
http://pixijs.download/release/docs/PIXI.filters.ColorMatrixFilter.html

**Comment by kburke3** [comment]
Can you change the fill color for the next time that it's drawn?

**Comment by bigtimebuddy** [comment]
In PixiAnimate, graphic drawing is compressed an array of commands & arguments. You'd need to replace the specific color in this array and then call this again, where `commands` is the array: 
```js
graphic.clear();
graphic.drawCommands(commands);
```

**Comment by kburke3** [comment]
Hi,
Thank you for this! I **finally** got it to work...

Going to add it here for posterity.

```javascript
//changes the fill (the 2nd member of this ShapesCache array in this example) to a decimal color value
PIXI.animate.ShapesCache.tint[20][1] = 16711680;

//create variables for the main timeline and movie clip graphics
var timeline = scene.stage.children[0];
var circleGraphics = timeline.circle_mc.children[0];

//call drawCommands passing the altered ShapesCache array
circleGraphics.drawCommands(PIXI.animate.ShapesCache.tint[20]);
```
