### ISSUE TITLE
Any method to get child ?

### ISSUE THREAD

**Issue by k8w** [jiborobot/pixi-animate#66]
As title.
For example `getChildAt` or `getChildByName`
Not find it in documentation...

**Comment by bigtimebuddy** [comment]
http://pixijs.download/release/docs/PIXI.Container.html#getChildAt

**Comment by k8w** [comment]
Only by index? Can getChildByName from a MovieClip ?

**Comment by k8w** [comment]
Got it.
Maybe I can use `xxx.children.find(v=>v.name==='XXX')`
