### ISSUE TITLE
Change loaders to NOT use convenience methods

### ISSUE THREAD

**Issue by stevenalanstark** [jiborobot/pixi-animate#73]
I've noticed some 'bad' practice with the loaders, according to pixi.js dev's.

If you take a look here [http://www.html5gamedevs.com/topic/18951-texture-not-in-texturecache-again/](http://www.html5gamedevs.com/topic/18951-texture-not-in-texturecache-again/), you will see that xerver states 

> Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Don't mix the loader and convenience methods. Write that line 50 times and you will be out of detention. Just use the loader, forget the convenience methods exist.

I was experiencing issues with the `fromFrame` method not having it's texture in the cache, due to this code in the SymbolLoader: 

```
PIXI.Texture.addTextureToCache(
	PIXI.Texture.fromFrame(url),
	resource.name
);
```

Using `PIXI.Texture.fromFrame` here is the issue. You're telling it to add a texture, but then tell it to fetch the texture as the first param, which is a logic error. The texture can't exist before adding it. This is why we shouldn't be mixing the loader and convenience methods. 

Instead, I've changed this to:

```
PIXI.Texture.addToCache(
  resource.texture,
  resource.name
);
```

it's cleaner, and uses the resource directly. This should be applied to all loaders.

**Comment by bigtimebuddy** [comment]
Good catch. Mind putting a PR together for this?

**Comment by stevenalanstark** [comment]
sure, I thought of that but I didn't review the other loaders. I'll put this together tomorrow.

**Comment by bigtimebuddy** [comment]
Thanks @stevenalanstark!
