### ISSUE TITLE
unable to install npm module by git url

### ISSUE THREAD

**Issue by stevenalanstark** [jiborobot/pixi-animate#76]
This may be 'by design', however I found that the package.json's files obj is defining only dist and libs, but those folders are compiled for the NPM publish and not part of the git repo. This means that installing the NPM module by the git url, not the NPM package name, is not supported.

Is this intentional?

**Comment by bigtimebuddy** [comment]
That is correct, it's only available on NPM, we do not check in built files. You can build it locally and link, if you'd like.

**Comment by stevenalanstark** [comment]
thank you for confirming.
